### ISSUE TITLE
Feature: User can search for a specific character

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/marvelous#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a specific character in the Marvel API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be brought to the the home page which doubles as the character search screen. There will be a text input for them to type in a character and hit the search button. If there is an exact match, it will move forward to their specific character profile page. If there isn't a match, it will show a message saying that there is no exact match found, along with a hint to try different variations or to check the spelling. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/220714330-e6faaeac-e40a-4cfe-8e35-4386c92ac022.png)

![image](https://user-images.githubusercontent.com/117682160/220714530-8e9dd290-b004-42c1-aa72-13484e2605e5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... create a `users` table, a `characters` table, and a `favorites` table.  
- [x] Update the `users` table of the `schema.sql` to save the username, hashed password, hashed emails, and a URL to their profile picture.
- [x] Update the `characters` table of the `schema.sql` to save that character's name, biography, profile picture URL, and the number of comic book appearances.
- [x] Update the `favorites` table of the `schema.sql` to link the `users` and `characters` tables with foreign keys
- [x] Update `data.sql` to ...have an insert function that takes the username and already-hashed password to store into the `users table
- [x] Update `data.sql` to upload the name, description, and image URL of a specific character into the `characters` table

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...set up a server to handle incoming requests and responses from the client-side of the application
- [x] Create an authentication method using md5 hashing to properly make requests to the Marvel API
- [x] Write a get request to the Marvel API to handle search requests from the client-side
- [x] Write a function to handle the response from the Marvel API to send the appropriate information back to the client-side
- [x] Set up error handling middleware to catch and log any errors and display a user-friendly message during the server's operation
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the navbar
- [x] Create a component to display the sub-navbar
- [x] Create a component to show the container information to house the `p` element the text field, and the search button
- [x] Create a component for the search button

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
