### ISSUE TITLE
Feature: User can view specific character pages to see their name, description, thumbnail, and number of comics they’ve appeared in

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/marvelous#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view specific character pages to see their name, description, thumbnail, and number of comics they’ve appeared in. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user. 

Upon successfully finding an exact match for a Marvel character, a page populates with the pertinent info showing their name, their profile picture, a biography (if available), and a number of how many total comic book appearances they currently have. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/220715745-fd14ec2a-cb52-4d88-b243-4b15d62a6aba.png)

![image](https://user-images.githubusercontent.com/117682160/220715768-a6b47e62-fa96-4eeb-9607-c2b077a4af4a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

No database changes are needed for this issue. 

### ☁️ Server Tasks

No server changes are needed for this issue. 

### ⚡ Client Tasks

- [x] Add a character page
- [x] Add a character component
- [x] Assign the values from the API server response to their respective elements
- [x] Implement React Router to switch between the home page and the character page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
