### ISSUE TITLE
Feature: User can sign up for an account

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/marvelous#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When at the sign-in page, they can click the option to create an account on a new page for registration that contains fields for username, password, confirm password, email, confirm username, a button to upload a profile picture, and a submit button to process the request. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/220725042-087be944-d5b3-46ab-8486-99246b991b0b.png)

![image](https://user-images.githubusercontent.com/117682160/220725071-185863cf-485a-4842-af1a-fc0d47b65ab4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

None needed at this stage. 

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... handle user registration
- [x] Update `server/index.js` to ... handle user sign in
- [x] Update `server/index.js` to ... handle user sign out
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ... show the profile menu when clicking on the profile icon
- [x] Add separate pages for registration and sign in
- [x] Change the profile menu contents to change depending on if the user is signed in
- [x] Implement React Hook Forms for the registration page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
