### ISSUE TITLE
Feature: User can log into and out of their existing account 

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/marvelous#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log into and out of their existing account

User can log into and out of their existing account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to sign in or sign out through clicking the profile icon on mobile screens, with an additional sign in button for desktop views available next to the profile icon. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/220725447-c703779e-4c04-4efd-a7ee-012b050e7705.png)

![image](https://user-images.githubusercontent.com/117682160/220725499-b464b124-f33c-4960-9b15-0165699c7ed2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

No changes needed at this stage. 

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...be able to log into a user's account with the correct password, using jwt tokens
- [x] Update `server/index.js` to be able to log out of the user's account
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the profile picture icon to display their background image if logged in
- [x] Update the profile menu component to have proper sign in and sign out functionality
- [x] Update the profile menu component to show different content if logged in, including the favorites list as well as the sign-out function

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
