### ISSUE TITLE
Feature: User can add and remove favorite characters from their account

### ISSUE THREAD

**Issue by joseph-w-valdez** [joseph-w-valdez/marvelous#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add and remove favorite characters from their account. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the character profile page, the user can click the star icon to favorite or unfavorite that character. A hollow star means it is currently unfavorited and a full star means it is currently favorited. The user can access the favorites list via the profile menu on all screen; or the hamburger menu in mobile screens; or the navbar for the favorites item in desktop screens. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117682160/220728434-a2c2a9ef-589d-488b-a8f9-b9f255c10721.png)

![image](https://user-images.githubusercontent.com/117682160/220728476-4ec2609a-7cbd-40a6-8b3c-144ae38138e2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

No changes needed at this stage. 

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... have a favorites endpoint that updates the `favorites` table to track all users' favorite characters.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a page for viewing the favorites page. 
- [x] Update the favorites `div` on the `character` page to toggle the heart being filled and empty
- [x] Add an handler for the `favorites` `div` on the `character` page to use an `axios.post` for the `favorites` endpoint
- [x] Create mapping function on the favorites page to show a list of all characters with an option to remove them from the list and to click them to get to their relevant character page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
